# Generated by Django 4.2.1 on 2023-05-29 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=500)),
                ('size', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='projects.category')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('subject', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Type_label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Text_pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_1', models.CharField(max_length=500)),
                ('paragraph_2', models.CharField(max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_project', to='projects.project')),
                ('type_label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_label', to='projects.type_label')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tag_project', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_project', to='projects.project')),
                ('type_label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_label', to='projects.type_label')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_project', to='projects.project')),
                ('type_label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_label', to='projects.type_label')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Action_TextPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_project', to='projects.project')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_textpair', to='projects.text_pair')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Action_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_project', to='projects.project')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_question', to='projects.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Action_Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_project', to='projects.project')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_document', to='projects.document')),
                ('tag', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tag_action', to='projects.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
