# Generated by Django 4.2.1 on 2023-05-29 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action_document',
            old_name='question',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='action_textpair',
            old_name='question',
            new_name='text_pair',
        ),
    ]
