# Generated by Django 4.2.1 on 2023-05-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_question_action_document_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action_document',
            name='tag',
        ),
        migrations.AddField(
            model_name='action_document',
            name='tag',
            field=models.ManyToManyField(to='projects.tag'),
        ),
    ]
