# Generated by Django 4.2.1 on 2023-05-29 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_action_document_tag_action_document_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='type_label',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='category_label', to='projects.category'),
        ),
    ]
